languages:
   JavaScript: true
engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "**.htm"
  - "**.html"
  - "**.js"
  - "**.css"
    
ratings:
   paths:
   - "**.js"

exclude_paths:
- "*.min.*"
- spec/**/*
